# Makes Alembic detect the models
from core.db import Base
from models.attendance import Attendance
from models.audit_log import AuditLog
from models.company import Company
from models.company_prep import CompanyPrepQuestion
from models.dashboard_snapshot import DashboardSnapshot
from models.department import Department
from models.faculty import Faculty
from models.faculty_schedule_entry import FacultyScheduleEntry
from models.interview_experience import InterviewExperience
from models.interview_question import InterviewQuestion
from models.interview_round import InterviewRound
from models.job_notification import JobNotification
from models.mark import Mark
from models.minor_degree import MinorDegree
from models.offer import Offer
from models.placement import Placement
from models.placement_application import PlacementApplication
from models.placement_drive import PlacementDrive
from models.placement_offer_v2 import PlacementOfferV2
from models.profile import Profile
from models.resume import Resume
from models.resume_analysis_cache import ResumeAnalysisCache
from models.resume_embedding import ResumeEmbedding
from models.resume_version import ResumeVersion
from models.profile import Profile
from models.user_role import UserRole
from models.student import Student
from models.resume_rule import ResumeRule
from models.placement_policy import PlacementPolicy
